IMMERSION/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'

  resources :newsletters, only: [:new, :create]

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
  end

  resources :startups, only: [:index, :show, :create, :update, :destroy]

  resources :events, only: [:index, :show, :create, :update, :destroy] do
    resources :attendances, except: :index
    collection do 
      get :search
    end
  end




  namespace :admin do
    root 'admin#index'
    resources :users
    resources :startups
    resources :events do
      resources :attendances
    end
    resources :attendances_submissions, only: [:index]
  end

  scope module: 'admin' do
    resources :newsletters, except: :create
    resources :activities
    resources :situations
  end


  get 'static/home'
  get '/gallery', to: 'static#gallery'
  # get '/search' => 'events#search', :as => 'search_page'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

IMMERSION/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :situation, optional: true
  belongs_to :activity, optional: true
  belongs_to :newsletter, optional: true
  has_many :attendances
  has_many :events, through: :attendances

  has_one_attached :avatar

  after_create :welcome_send
  def welcome_send
  	UserMailer.welcome_email(self).deliver_now
  end


  after_create :check_newsletter
  def check_newsletter
    existing_newsletter = Newsletter.find_by(email: self.email)
    if existing_newsletter != nil
      self.update!(newsletter: existing_newsletter)
    end
  end
end

IMMERSION/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :situation_id, :formation, :user_id, :description, :linked_in_url, :newsletter_id)
    end

    def is_right_user?
      @user = User.find(params[:id])
      unless @user.id == current_user.id
        flash[:danger] = 'This is not your account'
        redirect_to user_path(current_user)
      end
    end
end

IMMERSION/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_right_user?
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      if current_user.admin?
        format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :situation_id, :formation, :activity_id, :description, :linked_in_url, :newsletter_id, :admin)
    end

    def is_right_user?
      @user = User.find(params[:id])
      unless current_user.admin?
        unless @user.id == current_user.id
          flash[:danger] = 'This is not your account'
          redirect_to user_path(current_user)
        end
      end
    end
end

IMMERSION/app/helpers/users_helper.rb
module UsersHelper
end

IMMERSION/app/views/users/_form.html.erb
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :email %>
      <%= @user.email%>
    </div>

    <div class="field">
      <%= form.label :first_name %><br />
      <%= form.text_field :first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %><br />
      <%= form.text_field :last_name %>
    </div>

    <br/>
    <div class="field">
      <%= form.label :situation %><br />
      <%= form.select :situation_id, options_from_collection_for_select(Situation.all, :id, :title, @user.situation_id), { :prompt => 'Choose from list :'} %>
    </div>

    <div class="field">
      <%= form.label :formation %><br />
      <%= form.text_field :formation %>
    </div>

    <div class="field">
      <%= form.label :activity %><br />
      <%= form.select :activity_id, options_from_collection_for_select(Activity.all, :id, :name, @user.activity_id), { :prompt => 'Choose from list :'} %>
    </div>

    <br/>
    <div class="field">
      <%= form.label :description %><br />
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :linked_in_url %><br />
      <%= form.text_field :linked_in_url %>
    </div>

    <div class="field">
      <%= form.label :newsletter %><br />
      <%= form.text_field :newsletter %>
    </div>

    <br/>
    <div class="field">
      <%= form.label :description %><br />
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :linked_in_url %><br />
      <%= form.text_field :linked_in_url %>
    </div>

    <div class="field">
      <%= form.label :newsletter %><br />
      <%= form.text_field :newsletter %>
    </div>

=======
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

IMMERSION/app/views/users/edit.html.erb
<%= link_to 'Show', @user %> |
<% if current_user.admin? %>
  <%= link_to 'Back', admin_users_path %>
<% else %>
  <%= link_to 'Back', :root %>
<% end %>

<br/>
<div class="center">
  <h1>MODIFIER LE PROFIL</h1>
</div>
<br/>

<div class="center">

  <%= render 'form', user: @user %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path, :class =>"btn btn-primary" %>


</div>

IMMERSION/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<!-- this page is ugly sorry because this page is not for user-->
<h1 class="center">Users</h1>

<div class="container-fluid">
  <div class="row">
      <% @users.each do |user| %>
      <div class="card col-md-6 col-sm-12">
         <ul class="none">

          <li><strong>Email</strong> <%= user.email %></li>
          <li>
            <strong>First name</strong> <%= user.first_name %>
            <strong>Last name</strong> <%= user.last_name %>
          </li>

          <li>
            <strong>Situation</strong>
            <% if user.situation == nil %>
              <%= user.situation %>
            <% else %>
              <%= user.situation.title %>
            <% end %>
          </li>

          <li>
            <strong>Formation</strong>
          <%= user.formation %>
            <strong>Activity</strong>
            <% if user.activity == nil %>
              <%= user.activity %>
            <% else %>
              <%= user.activity.name %>
            <% end %>
          </li>
          <li>
            <strong>Description</strong> <%= user.description %>
          </li>
          <li>
            <strong>Linkedin</strong> <%= user.linked_in_url %>
            <strong>Newsletter</strong> <%= user.newsletter %>
          </li>
          <li>
            <strong>Created at</strong> <%= user.created_at %>
            <strong>Updated at</strong> <%= user.updated_at %>
          </li>
          <li>
            <%= link_to 'Show', user %>&nbsp;
            <%= link_to 'Edit', edit_user_path(user) %>&nbsp;
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        </ul>
        </div>
      <% end %>
    </div> <br />
    <div class="center">
      <%= link_to 'Back', :back, :class =>"btn btn-primary" %>
    </div>
</div>

IMMERSION/app/views/users/show.html.erb
    <p id="notice"><%= notice %></p>

<div class="container"> <br /> <br />

    <p>
      <strong>Email:</strong>
      <%= @user.email %><br/>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>

    <p>
      <strong>Situation:</strong>
      <% if @user.situation == nil %>
        <%= @user.situation %>
      <% else %>
        <%= @user.situation.title %>
      <% end %>
    </p>

    <p>
      <strong>Formation:</strong>
      <%= @user.formation %>
    </p>

    <p>
      <strong>Activity:</strong>
      <% if @user.activity == nil %>
        <%= @user.activity %>
      <% else %>
        <%= @user.activity.name %>
      <% end %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @user.description %>
    </p>

    <p>
      <strong>Linkedin:</strong>
      <%= @user.linked_in_url %>
    </p>

    <p>
      <strong>Newsletter:</strong>
      <%= @user.newsletter %>
    </p>

    <p>
      <strong>Member since:</strong>
      <%= @user.created_at %>
    </p>

    <p>
      <strong>Last profile update:</strong>
      <%= @user.updated_at %>
    </p>

    <% if @user.first_name != nil %>
      <h2><strong>Registration of <%= @user.first_name %> :</strong></h2>
    <% else %>
       <h3><strong>Registration of this user :</strong></h3>
    <% end %><br />

    <% @user.events.each do |user_attendances| %>
    <ul class="none">
        <li>Event:    <%= user_attendances.title %></li>
        <li>Date:     <%= user_attendances.start_datetime %></li>
        <li><%= link_to "Details &raquo;".html_safe, event_path(user_attendances), :class =>'btn btn-sm btn-outline-secondary' %> </li>
        <li> </li>
    </ul> <br />
    <% end %>

    <p id="notice"><%= notice %></p>

<div class="container"> <br /> <br />

    <p>
      <strong>Email:</strong>
      <%= @user.email %><br/>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>

    <p>
      <strong>Situation:</strong>
      <% if @user.situation == nil %>
        <%= @user.situation %>
      <% else %>
        <%= @user.situation.title %>
      <% end %>
    </p>

    <p>
      <strong>Formation:</strong>
      <%= @user.formation %>
    </p>

    <p>
      <strong>Activity:</strong>
      <% if @user.activity == nil %>
        <%= @user.activity %>
      <% else %>
        <%= @user.activity.name %>
      <% end %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @user.description %>
    </p>

    <p>
      <strong>Linkedin:</strong>
      <%= @user.linked_in_url %>
    </p>

    <p>
      <strong>Newsletter:</strong>
      <%= @user.newsletter %>
    </p>

    <p>
      <strong>Member since:</strong>
      <%= @user.created_at %>
    </p>

    <p>
      <strong>Last profile update:</strong>
      <%= @user.updated_at %>
    </p>

    <% if @user.first_name != nil %>
      <h2><strong>Registration of <%= @user.first_name %> :</strong></h2>
    <% else %>
       <h3><strong>Registration of this user :</strong></h3>
    <% end %><br />

    <% @user.events.each do |user_attendances| %>
    <ul class="none">
        <li>Event:    <%= user_attendances.title %></li>
        <li>Date:     <%= user_attendances.start_datetime %></li>
        <li><%= link_to "Details &raquo;".html_safe, event_path(user_attendances), :class =>'btn btn-sm btn-outline-secondary' %> </li>
        <li> </li>
    </ul> <br />
    <% end %>


    <h3><strong>Profil Page</strong></h3>
    <p>Bienvenue sur la page Photo de profil<%=@user.id%></p>

    <h3>Avatar actuel</h3>
    <%if @user.avatar.attached?%>
      <%= image_tag @user.avatar, alt: 'avatar' %>
    <%else%>
      <p>=== il n'y a pas encore d'avatar ===</p>
    <%end%> <br />

    <h3>Switch picture profile </h3>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
      <%= file_field_tag :avatar%>

      <%= submit_tag "valider", :class => 'btn btn-success'%>
    <% end %> <br />
  <div class="center">
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', user_path(@user), :class=>"btn btn-primary" %>
  </div>
</div>

<br/>
<br/>