IMMERSION/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'

  resources :newsletters, only: [:new, :create]

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
  end

  resources :startups, only: [:index, :show, :create, :update, :destroy]

  resources :events, only: [:index, :show, :create, :update, :destroy] do
    resources :attendances, except: :index
    collection do 
      get :search
    end
  end




  namespace :admin do
    root 'admin#index'
    resources :users
    resources :startups
    resources :events do
      resources :attendances
    end
    resources :attendances_submissions, only: [:index]
  end

  scope module: 'admin' do
    resources :newsletters, except: :create
    resources :activities
    resources :situations
  end


  get 'static/home'
  get '/gallery', to: 'static#gallery'
  # get '/search' => 'events#search', :as => 'search_page'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

IMMERSION/app/models/situation.rb
class Situation < ApplicationRecord
  has_many :users

  validates :title,
  presence: true
end

IMMERSION/app/controllers/admin/situations_controller.rb
class Admin::SituationsController < Admin::BaseController
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  # GET /situations
  # GET /situations.json
  def index
    @situations = Situation.all
  end

  # GET /situations/1
  # GET /situations/1.json
  def show
  end

  # GET /situations/new
  def new
    @situation = Situation.new
  end

  # GET /situations/1/edit
  def edit
  end

  # POST /situations
  # POST /situations.json
  def create
    @situation = Situation.new(situation_params)

    respond_to do |format|
      if @situation.save
        format.html { redirect_to @situation, notice: 'Situation was successfully created.' }
        format.json { render :show, status: :created, location: @situation }
      else
        format.html { render :new }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /situations/1
  # PATCH/PUT /situations/1.json
  def update
    respond_to do |format|
      if @situation.update(situation_params)
        format.html { redirect_to @situation, notice: 'Situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @situation }
      else
        format.html { render :edit }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /situations/1
  # DELETE /situations/1.json
  def destroy
    @situation.destroy
    respond_to do |format|
      format.html { redirect_to situations_url, notice: 'Situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situation
      @situation = Situation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def situation_params
      params.require(:situation).permit(:title)
    end
end

IMMERSION/app/controllers/situations_controller.rb
class SituationsController < ApplicationController
end

IMMERSION/app/helpers/situations_helper.rb
module SituationsHelper
end

IMMERSION/app/views/situations/_form.html.erb
<%= form_with(model: situation, local: true) do |form| %>
  <% if situation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(situation.errors.count, "error") %> prohibited this situation from being saved:</h2>

      <ul>
      <% situation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

IMMERSION/app/views/situations/edit.html.erb
<h1>Editing Situation</h1>

<%= render 'form', situation: @situation %>

<%= link_to 'Show', @situation %> |
<%= link_to 'Back', situations_path, :class =>"btn btn-primary" %>

IMMERSION/app/views/situations/index.html.erb
<p id="notice"><%= notice %></p><br/>

<h1 class="center">Situations</h1>
<div class="container">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @situations.each do |situation| %>
        <tr>
          <td><%= situation.title %>&nbsp;</td>
          <td><%= link_to 'Show', situation %>&nbsp;</td>
          <td><%= link_to 'Edit', edit_situation_path(situation) %>&nbsp;</td>
          <td><%= link_to 'Destroy', situation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Situation', new_situation_path, :class => "btn btn-success" %>
</div><br /><br />
<div class="center"><%= link_to 'Back',admin_root_path , :class => "btn btn-primary"%></div>

IMMERSION/app/views/situations/new.html.erb
<div class="center"><br/>
  <h1>New Situation</h1>

  <%= render 'form', situation: @situation %><br /><br />

  <%= link_to 'Back', situations_path, :class =>"btn btn-primary" %>
</div>

IMMERSION/app/views/situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @situation.title %>
</p>

<%= link_to 'Edit', edit_situation_path(@situation) %> |
<%= link_to 'Back', situations_path, :class =>"btn btn-primary" %>