IMMERSION/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'

  resources :newsletters, only: [:new, :create]

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
  end

  resources :startups, only: [:index, :show, :create, :update, :destroy]

  resources :events, only: [:index, :show, :create, :update, :destroy] do
    resources :attendances, except: :index
    collection do 
      get :search
    end
  end




  namespace :admin do
    root 'admin#index'
    resources :users
    resources :startups
    resources :events do
      resources :attendances
    end
    resources :attendances_submissions, only: [:index]
  end

  scope module: 'admin' do
    resources :newsletters, except: :create
    resources :activities
    resources :situations
  end


  get 'static/home'
  get '/gallery', to: 'static#gallery'
  # get '/search' => 'events#search', :as => 'search_page'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

IMMERSION/app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :startup
  has_many :attendances
  has_many :users, through: :attendances
  
  geocoded_by :adress
  after_validation :geocode, if: :adress_changed?
  
  validates :title,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :start_datetime,
  presence: true
  validate :start_datetime_ok?

  validates :duration,
  presence: true
  validate :duration_modulo_5?

  validates :description,
  presence: true,
  length: {in: 20..1000, message: ' must be between 20 and 1000 characters long'}

  validates :short_location,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :adress,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :zip_code,
  presence: true,
  numericality: { greater_than: 9999, less_than: 100000, message: ' must be between 9999 and  100000'}

  validates :city,
  presence: true,
  length: {in: 1..140, message: ' must be between 5 and 140 characters long'}
  
  def self.search(params)
    @parameter = params[:search].downcase
    events = Event.where("lower(title) LIKE ? or lower(description) LIKE ? or lower(short_location) LIKE ?", "%#{@parameter}%","%#{@parameter}%","%#{@parameter}%") if params[:search].present?
    events
  end
  
  def end_date
  	return start_datetime + (duration * 60)
  end

  private

  def start_datetime_ok?
  	errors.add(:start_datetime, " can't be in the past") unless
  	start_datetime.present? && start_datetime > Date.today
  end

  def duration_modulo_5?
  	errors.add(:duration, " must be positive and a multiple of 5") unless
  	duration.to_i % 5 == 0 && duration.to_i > 0
  end
end

IMMERSION/app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order('start_datetime asc')
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_datetime, :duration, :description, :short_location, :adress, :zip_code, :city, :startup_id)
    end
end

IMMERSION/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index

    @events = Event.all.order('start_datetime asc')

    @events = Event.all
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.title
    end

  end

  # GET /events/1
  # GET /events/1.json
  def show
    @events = Event.where(id: params[:id])
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow event.title
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].blank?
      @events = Event.all
    else
      @events = Event.search(params)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_datetime, :duration, :description, :short_location, :adress, :zip_code, :city, :startup_id, :latitude, :longitude)
    end
end

IMMERSION/app/helpers/events_helper.rb
module EventsHelper
end

IMMERSION/app/views/events/_card_event.html.erb
<div class="container center-div">

<div class="row">


    <div class="card text-white bg-primary mb-3 ml-3 mr-3" style="max-width: 20rem;">


      <div class="card-header">TEST</div>
      <img class="card-img-top" src=<%= asset_path 'photo1.jpg' %> alt="Card image cap">

      <div class="card-body">
      <p class="card-text"><center><a class="btn btn-secondary btn-md" href="#" role="button">Preview</a> <a class="btn btn-secondary btn-md" href="#" role="button">Subscribe</a></center></p>


</div>
</div>
</div>
</div>

IMMERSION/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div> <br />

  <div class="field">
    <%= form.label :start_datetime %><br />
    <%= form.datetime_select :start_datetime %>
  </div><br />

  <div class="field">
    <%= form.label :duration %> (hour) <br />
    <%= form.number_field :duration %>
  </div><br />

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description %>
  </div><br />

  <div class="field">
    <%= form.label :short_location %><br />
    <%= form.text_field :short_location, placeholder:"Notre Dame" %>
  </div>

  <div class="field">
    <%= form.label :adress %><br />
    <%= form.text_field :adress, placeholder:"6 pl J Paul II Prv Notre Dame" %>
  </div>

  <div class="field">
    <%= form.label :zip_code %><br />
    <%= form.text_field :zip_code, placeholder:"75004"%>
  </div>

  <div class="field">
    <%= form.label :city %><br />
    <%= form.text_field :city, placeholder:"Paris" %>
  </div>

  <div class="field">
    <%= form.label :startup %><br />
    <%= form.select :startup_id, options_from_collection_for_select(Startup.all, :id, :name, @event.startup_id), { :prompt => 'Choose from list :'} %>
  </div> <br />

  <%= form.hidden_field :event, :value => params[:latitude] %>
  <%= form.hidden_field :event, :value => params[:longitude] %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

IMMERSION/app/views/events/_google_map_event.html.erb
<div class='center' style="width: 1200px">
  <div id="map" style='width: 1200px; height: 400px; margin-bottom: 4.5em;'></div>
</div>
<script type="text/javascript">

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

IMMERSION/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path, :class =>"btn btn-primary" %>

IMMERSION/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>




<br/>

<!-- <div class="container-fluid"> -->

  <h1 class="my-5 text-center">LES IMMERSIONS</h1>



  <div class ="container">

    <div  class="row">
      <% @events.each do |event| %>

          <div class=" p-3 col-lg-4 col-sm-12 ">
            <div class="card p-3 shadow">
              <img class="card-img-top  img-border" src="<%= asset_path 'photo2.jpg' %>" alt="Card image cap"/>
              <div class="center mt-2"><%= event.title.upcase %></div>
                <div class="card-body">
                  <ul class="none">
                      <li><%= event.start_datetime%></li>
                      <li><%= event.duration %> min</li><br />
                      <li class="card-text"><%= event.description %></li><br />

                      <li><%= event.short_location %></li>
                      <li><%= event.adress %></li>

                      <li> <!-- if user = register -->
                        <%= event.zip_code %>
                        <%= event.city %>
                      </li>
                  </ul><br />

                </div>
                <div class="card-foot center">
                  <a role="button"<%= link_to "EN VOIR +", event_path(event.id), :class =>'btn btn-sm btn-primary'%></a>
                  <a role="button"><%= link_to 'Se pré-inscrire', new_event_attendance_path(event.id), :class=>"btn btn-sm btn-primary"%></a><br />
                </div>

              </div>
            </div>

          <% end %>
        </div>


    </div>





<div class="center mb-5">
  <% if current_user && current_user.admin? %>
    <%= link_to 'New Event', new_admin_event_path %> |
    <%= link_to 'BACK', :admin_root, :class => "btn btn-primary" %>
  <% else %>
    <%= link_to '<< BACK', :root, :class=> "btn btn-primary" %>
  <% end %>

</div>

IMMERSION/app/views/events/new.html.erb
<br />
<div class ="center">
  <h2>New Event</h2>

  <%= render 'form', event: @event %>

  <br /><%= link_to 'Back', events_path, :class=>"btn btn-primary" %>
</div>

IMMERSION/app/views/events/search.html.erb
<div class="center">
<h1>RÉSULTATS DE LA RECHERCHE</h1>

<div class="container center-div">
<!--section card-->
<div class="row">

<% @events.each do |event|%>
<!-- classe des cards-->
    <div class="card text-white bg-primary mb-3 ml-3 mr-3" style="max-width: 20rem;">
<!-- début de la 1ere card-->


      <div class="card-header"><%= event.title %> </div>
      <img class="card-img-top" src=<%= asset_path 'photo1.jpg' %> alt="Card image cap">

      <div class="card-body">
      <p class="card-text"><center><%= event.description %><br>
      <%= event.short_location %><br>
      <a class="btn btn-secondary btn-md" href="#" role="button">Preview</a>
      <a class="btn btn-secondary btn-md" href="#" role="button">Shop now</a>
      </center></p>

    </div>
    </div>
<% end %>
</div>
</div>
</div>
<div class="center">
<a <%= link_to "BACK", :back, :class =>"btn btn-primary" %></a>
</div>
<br/>
<br/>

IMMERSION/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<!-- GOOGLE MAP -->
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=geometry&sensor=false&key=[YOUR_KEY_API]"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>
  <!-- GOOGLE MAP -->


  <p id="notice"><%= notice %></p>




<br />
      <div class="container">
            <h1 class="center"><%= @event.title.upcase %></h1>
            <p class="lead">
              <strong>Start date:</strong>
              <%= @event.start_datetime %>
            </p>
            <p class="lead">
              <strong>Duration:</strong>
              <%= @event.duration %>
            </p>

            <p class="lead">
              <strong>End date:</strong>
              <%= @event.end_date %>
            </p>

            <p class="lead">
              <strong>Description:</strong>
              <%= @event.description %>
            </p>

            <p class="lead">
              <strong>Short location:</strong>
              <%= @event.short_location %>
            </p>

            <p class="lead">
              <strong>Adress:</strong>
              <%= @event.adress %>
            </p>

            <p class="lead">
              <strong>Zip code:</strong>
              <%= @event.zip_code %>
            </p>

            <p class="lead">
              <strong>City:</strong>
              <%= @event.city %>
            </p>

          <p class="lead">
            <strong>Startup:</strong>
            <%= @event.startup.name %>
            <%= link_to 'Startup', startup_path(@event.startup.id) %>
          </p><br/>

          <br />
          <br />
          <div class="card">
            <div class="shadow"><%= image_tag 'work.jpg' %></div>
          </div><br />

          <h3>Attendances</h3>
          <% for attendance in @event.attendances %>
          <p class="lead">
            <%= attendance.motivation %>
          </p>
          <% end %>

            <br />
            <br />

              <div id="map"><%= render 'google_map_event' %></div> <br />

              <ul class="list-group list-group-flush">
                <strong><h3>Registration for this event :</h3>
                <p><%= @event.attendances.count %> registrations</p></strong>

                <% @event.users.each do |event_attendances| %>

                    <li class="list-group-item">

                      &nbsp; <%= event_attendances.first_name %>
                      &nbsp; <%= event_attendances.email %>
                      <%= link_to "Details &raquo;".html_safe, user_path(event_attendances), :class =>'btn btn-sm btn-outline-secondary float-right' %>
                    </li>
                <% end %>
              </ul><br />
              <div class="center">

                <% if current_user && current_user.admin? %>
                  <%= link_to 'Edit', edit_admin_event_path(@event) %> |
                  <%= link_to 'Ajouter une pré-inscription', new_event_attendance_path(@event) %> |
                  <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %> |
                <% elsif @event.users.include?(current_user) %>
                  <% att = Attendance.find_by(user_id: current_user, event_id: @event) %>
                    <%if att.reviewed? && att.validated? %>
                      <%= link_to 'Mon inscription', user_path(current_user) %> |
                    <%elsif att.reviewed? && att.validated? == false %>
                      <%= link_to 'Ma pré-inscription', user_path(current_user) %> |
                    <% else %>
                      <%= link_to 'Déjà pré-inscrit(e)', user_path(current_user) %> |
                    <% end %>
                <% else %>
                  <%= link_to 'Se pré-inscrire', new_event_attendance_path(@event) %> |
                <% end %>
                <%= link_to 'BACK', :events, :class=>"btn btn-primary" %>

              </div>
          </div>