IMMERSION/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'static#home'

  resources :newsletters, only: [:new, :create]

  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
  end

  resources :startups, only: [:index, :show, :create, :update, :destroy]

  resources :events, only: [:index, :show, :create, :update, :destroy] do
    resources :attendances, except: :index
    collection do 
      get :search
    end
  end




  namespace :admin do
    root 'admin#index'
    resources :users
    resources :startups
    resources :events do
      resources :attendances
    end
    resources :attendances_submissions, only: [:index]
  end

  scope module: 'admin' do
    resources :newsletters, except: :create
    resources :activities
    resources :situations
  end


  get 'static/home'
  get '/gallery', to: 'static#gallery'
  # get '/search' => 'events#search', :as => 'search_page'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

IMMERSION/app/models/activity.rb
class Activity < ApplicationRecord
  has_many :users

  validates :name,
  presence: true
end

IMMERSION/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

IMMERSION/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :motivation,
  presence: true,
  length: {in: 20..1000, message: ' must be between 20 and 1000 characters long'}

  validates :comment,
  presence: true,
  length: {in: 20..1000, message: ' must be between 20 and 1000 characters long'}
end

IMMERSION/app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :startup
  has_many :attendances
  has_many :users, through: :attendances
  
  geocoded_by :adress
  after_validation :geocode, if: :adress_changed?
  
  validates :title,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :start_datetime,
  presence: true
  validate :start_datetime_ok?

  validates :duration,
  presence: true
  validate :duration_modulo_5?

  validates :description,
  presence: true,
  length: {in: 20..1000, message: ' must be between 20 and 1000 characters long'}

  validates :short_location,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :adress,
  presence: true,
  length: {in: 1..140, message: ' must be between 1 and 140 characters long'}

  validates :zip_code,
  presence: true,
  numericality: { greater_than: 9999, less_than: 100000, message: ' must be between 9999 and  100000'}

  validates :city,
  presence: true,
  length: {in: 1..140, message: ' must be between 5 and 140 characters long'}
  
  def self.search(params)
    @parameter = params[:search].downcase
    events = Event.where("lower(title) LIKE ? or lower(description) LIKE ? or lower(short_location) LIKE ?", "%#{@parameter}%","%#{@parameter}%","%#{@parameter}%") if params[:search].present?
    events
  end
  
  def end_date
  	return start_datetime + (duration * 60)
  end

  private

  def start_datetime_ok?
  	errors.add(:start_datetime, " can't be in the past") unless
  	start_datetime.present? && start_datetime > Date.today
  end

  def duration_modulo_5?
  	errors.add(:duration, " must be positive and a multiple of 5") unless
  	duration.to_i % 5 == 0 && duration.to_i > 0
  end
end

IMMERSION/app/models/newsletter.rb
class Newsletter < ApplicationRecord
  has_one :user

  validates :email,
  presence: true

  after_create :check_user
  def check_user
    existing_user = User.find_by(email: self.email)
    if existing_user != nil
      existing_user.update!(newsletter: self)
    end
  end
end

IMMERSION/app/models/situation.rb
class Situation < ApplicationRecord
  has_many :users

  validates :title,
  presence: true
end

IMMERSION/app/models/startup.rb
class Startup < ApplicationRecord
  has_many :events

  validates :name,
  presence: true

  validates :catch_phrase,
  presence: true

  validates :website_url,
  presence: true

  validates :description,
  presence: true
end

IMMERSION/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :situation, optional: true
  belongs_to :activity, optional: true
  belongs_to :newsletter, optional: true
  has_many :attendances
  has_many :events, through: :attendances

  has_one_attached :avatar

  after_create :welcome_send
  def welcome_send
  	UserMailer.welcome_email(self).deliver_now
  end


  after_create :check_newsletter
  def check_newsletter
    existing_newsletter = Newsletter.find_by(email: self.email)
    if existing_newsletter != nil
      self.update!(newsletter: existing_newsletter)
    end
  end
end

IMMERSION/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_right_user?
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      if current_user.admin?
        format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :situation_id, :formation, :activity_id, :description, :linked_in_url, :newsletter_id, :admin)
    end

    def is_right_user?
      @user = User.find(params[:id])
      unless current_user.admin?
        unless @user.id == current_user.id
          flash[:danger] = 'This is not your account'
          redirect_to user_path(current_user)
        end
      end
    end
end

IMMERSION/app/helpers/activities_helper.rb
module ActivitiesHelper
end

IMMERSION/app/helpers/application_helper.rb
module ApplicationHelper
  def devise_flash
  if controller.devise_controller? && resource.errors.any?
    flash.now[:error] = flash[:error].to_a.concat resource.errors.full_messages
    flash.now[:error].uniq!
  end
end
end

IMMERSION/app/helpers/attendances_helper.rb
module AttendancesHelper
end

IMMERSION/app/helpers/avatars_helper.rb
module AvatarsHelper
end

IMMERSION/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
  end
end

IMMERSION/app/helpers/events_helper.rb
module EventsHelper
end

IMMERSION/app/helpers/newsletters_helper.rb
module NewslettersHelper
end

IMMERSION/app/helpers/situations_helper.rb
module SituationsHelper
end

IMMERSION/app/helpers/startups_helper.rb
module StartupsHelper
end

IMMERSION/app/helpers/static_helper.rb
module StaticHelper
end

IMMERSION/app/helpers/users_helper.rb
module UsersHelper
end

IMMERSION/app/views/admin/admin/index.html.erb
<h1 class="center">Welcome Administrateur</h1>

<div class="container">
		<%= link_to "My Profile", user_path(current_user) %>

		<h3>Newsletters</h3>
		<ul class="none">
			<li><%= link_to 'Index Newsletters', newsletters_path, :class => "btn btn-outline-secondary"%>&nbsp;&nbsp;
					<%= link_to 'New Newsletter', new_newsletter_path, :class => "btn btn-outline-primary" %>
			</li>
		</ul>

		<h3>Users</h3>
		<ul class="none">
			<li><%= link_to 'Index Users', admin_users_path , :class => "btn btn-outline-secondary"%></li>
		</ul>

		<h3>Activities</h3>
		<ul class="none">
			<li>
				<%= link_to 'Index Activities', activities_path, :class => "btn btn-outline-secondary" %>
				<%= link_to 'New Activity', new_activity_path, :class => "btn btn-outline-primary" %>
			</li>
		</ul>

		<h3>Situations</h3>
		<ul class="none">
			<li>
				<%= link_to 'Index Situations', situations_path, :class => "btn btn-outline-secondary" %>
				<%= link_to 'New Situation', new_situation_path, :class => "btn btn-outline-primary" %>
			</li>
		</ul>

		<h3>Startups</h3>
		<ul class="none">
			<li>
			<%= link_to 'Index Startups', startups_path, :class => "btn btn-outline-secondary" %>
			<%= link_to 'New Startup', new_admin_startup_path, :class => "btn btn-outline-primary" %>
			</li>
		</ul>

		<h3>Events</h3>
		<ul class="none">
			<li>
				<%= link_to 'Index Events', events_path, :class => "btn btn-outline-secondary" %>
				<%= link_to 'New Event', new_admin_event_path, :class => "btn btn-outline-primary" %>
			</li>
		</ul>

		<h3>Attendances Submissions</h3>
		<ul class="none">
			<li><%= link_to "#{Attendance.where(reviewed: false).count} new submissions ! &raquo;".html_safe, admin_attendances_submissions_path %></li>
			<li><%= Attendance.where(reviewed: false).count %> new submissions !</li>
			<li><%= link_to 'Index', admin_attendances_submissions_path %></li>
		</ul>
	</div>

<div class="center">
	<%= link_to 'Back', :back, :class => "btn btn-primary" %> |
	<%= link_to 'Home', :root, :class => "btn btn-secondary" %>
</div>

IMMERSION/app/views/layouts/_footer.html.erb
<div class="footer">
   <div class="container">
        <div class="row">
    
          <div class="col-lg-12">
            <center><b>STARTUP IMMERSION © 2019</b></center>
          </div>
        </div>
    </div>
</div>

IMMERSION/app/views/layouts/_messages.html.erb
<% devise_flash %>

<%# <% devise_flash %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

IMMERSION/app/views/layouts/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <a class="navbar-brand" href="/">
    <img src=<%= asset_path 'logo_transparent2.png' %> width="120" height="120" alt="">
  </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "LES IMMERSIONS", events_path, class: "nav-link" %>
          </li>
             <li class="nav-item active">
            <%= link_to "GALERIE", gallery_path, class: "nav-link" %>
          </li>

        </ul>
      </div>

        <% if user_signed_in?  %>
                    <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              DÉCONNEXION
            </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="<%= user_path(current_user.id) %>">MON PROFIL</a>
                  <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="delete" >DÉCONNEXION</a>
                </div>
        
          </div>

        <% else  %>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              CONNEXION
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="<%= new_user_session_path %>">SE CONNECTER</a>
              <a class="dropdown-item" href="<%= new_user_registration_path %>">CRÉER UN COMPTE</a>
            </div>
          </div>

        <% end  %>

    </nav>

IMMERSION/app/views/layouts/_search_bar.html.erb
<div class="center">
	<p> Tu cherches les immersions d'une start-up en particulier ?</p>
<%= form_tag(search_events_path, :method => "get",:class => "") do %>
   <%= search_field_tag :search, params[:search], placeholder: "Rechercher une start-up...", class: "search" %>

   <%= button_tag "Rechercher", :class => 'btn btn-secondary',:name => nil%>
<% end %>
</div>

IMMERSION/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Startup Immersion</title>
      <link rel="icon" href=<%=asset_path 'favicon.png' %> type="image/icon type">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/messages' %>
    <%= render 'layouts/navbar' %>
   
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>